# Markdownlint configuration for documentation-heavy projects
{
  # Line length - allow longer lines for better readability in documentation
  "MD013": {
    "line_length": 200,
    "code_blocks": false,
    "tables": false
  },

  # Allow raw HTML (useful for complex documentation)
  "MD033": false,

  # Allow duplicate headings (common in documentation sections)
  "MD024": {
    "siblings_only": true
  },

  # Allow emphasis as headers (for FAQ sections, etc.)
  "MD036": false,

  # Fenced code blocks - encourage language specification but don't require it
  "MD040": false,

  # Allow trailing punctuation in headers
  "MD026": false,

  # First line in file - allow any format
  "MD041": false,

  # Blanks around headers - more flexible
  "MD022": {
    "lines_above": 1,
    "lines_below": 1
  },

  # List marker style - force asterisk to match release pipeline
  "MD004": {
    "style": "asterisk"
  },

  # List indentation
  "MD007": {
    "indent": 2
  },

  # Allow both ordered and unordered lists to start with 1
  "MD029": {
    "style": "one_or_ordered"
  }
}
